name: build_images

on:
  push:
  workflow_dispatch:

env:
  REF_NAME: ${{github.ref_name}}
  ROME_SDK_REF_NAME: main

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout openzeppelin-contracts repository'
        uses: actions/checkout@v4
        with:
          # path: openzeppelin-contracts
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build openzeppelin-contracts image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: romelabs/openzeppelin-contracts:${{env.REF_NAME}}
          labels: romelabs/openzeppelin-contracts:${{env.REF_NAME}}

      - name: 'Set latest tag'
        if: |
          ( ${{github.ref_name}} == 'main' )
        run: |
          
          docker pull romelabs/openzeppelin-contracts:${REF_NAME}
          docker tag romelabs/openzeppelin-contracts:${REF_NAME} romelabs/openzeppelin-contracts:latest
          docker push romelabs/openzeppelin-contracts:latest
